var date = new Date()
//set
date.setDate(25)
console.log(date)
date.setFullYear(2027)
console.log(date)
date.setMonth(11)
console.log(date)
date.setHours(10)
console.log(date)
date.setMinutes(30)
console.log(date)
date.setSeconds(45)
console.log(date)
date.setMilliseconds(123)
console.log(date)
date.setTime(123)
console.log(date)
