var date = new Date()
console.log(date)
console.log("Get Date...",date.getDate())
console.log("Get Day...",date.getDay())
console.log("Get Full Year...",date.getFullYear())
console.log("Get Month...",date.getMonth())
console.log("Get Hours...",date.getHours())
console.log("Get Minutes...",date.getMinutes())
console.log("Get Seconds...",date.getSeconds())
console.log("Get Milliseconds...",date.getMilliseconds())
console.log("Get Time...",date.getTime())

console.log("Get UTC Date...",date.getUTCDate())
console.log("Get UTC Day...",date.getUTCDay())
console.log("Get UTC Full Year...",date.getUTCFullYear())
console.log("Get UTC Month...",date.getUTCMonth())
console.log("Get UTC Hours...",date.getUTCHours())
console.log("Get UTC Minutes...",date.getUTCMinutes())
console.log("Get UTC Seconds...",date.getUTCSeconds())
console.log("Get UTC Milliseconds...",date.getUTCMilliseconds())
